// LOG IN, CHANGE AND RESET PASSWORD

// login action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// send change password email action types
export const SEND_CHANGE_PASS_EMAIL_REQUEST = 'SEND_CHANGE_PASS_EMAIL_REQUEST';
export const SEND_CHANGE_PASS_EMAIL_SUCCESS = 'SEND_CHANGE_PASS_EMAIL_SUCCESS';
export const SEND_CHANGE_PASS_EMAIL_FAILURE = 'SEND_CHANGE_PASS_EMAIL_FAILURE';

// verify change password action types
export const VERIFY_CHANGE_PASS_REQUEST = 'VERIFY_CHANGE_PASS_REQUEST';
export const VERIFY_CHANGE_PASS_SUCCESS = 'VERIFY_CHANGE_PASS_SUCCESS';
export const VERIFY_CHANGE_PASS_FAILURE = 'VERIFY_CHANGE_PASS_FAILURE';

// reset password action types
export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILURE = 'RESET_PASS_FAILURE';

// SIGN UP AND SENDING OTP TO VERIFY EMAIL

// sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//sending OTP to email to verify
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// verify token
export const VERIFY_TOKEN_REQUEST = 'VERIFY_TOKEN_REQUEST';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAILURE = 'VERIFY_TOKEN_FAILURE';